<a href="https://colab.research.google.com/github/yuzzaf/Course-Machine-Learning/blob/main/UAS/Excerxise_Chapter_00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Nama: Muhammad Yuzzaf Ibrahim Azzumarafi**

**NIM: 1103200082**


**UAS**


#**Chapter 00 PyTorch Fundamentals**


##**Import Pytorch**

##Introduction Tensor

Tensor adalah struktur data dasar yang digunakan untuk menyimpan dan memanipulasi data. Tensor mirip dengan matriks atau array multidimensi, tetapi dengan fleksibilitas tambahan. Tensors dapat memiliki dimensi (rank) yang bervariasi, yang memungkinkan mereka mewakili berbagai jenis data, mulai dari skalar (0D) hingga vektor (1D), matriks (2D), hingga tensor dengan dimensi yang lebih tinggi.

Dalam PyTorch, tensor dapat digunakan untuk menyimpan data numerik, dan mereka mendukung operasi matematika yang efisien. Misalnya, tensor dapat digunakan untuk merepresentasikan input dan output dalam jaringan saraf, dan operasi tensor dapat diterapkan untuk melakukan perhitungan yang melibatkan transformasi linier, aktivasi, dan fungsi lainnya.

Berikut adalah beberapa contoh operasi yang dapat dilakukan dengan tensor di PyTorch:

*   Penjumlahan dan Pengurangan: Menambah atau mengurangkan tensor.
*   Perkalian dan Pembagian: Melakukan operasi perkalian atau pembagian dengan tensor.
*   Indeks dan Irisan: Mengakses atau memperoleh subset dari tensor menggunakan indeks atau irisan.
*   Operasi Matriks: Transposisi, perkalian matriks, dan operasi matriks lainnya.

Tensor memberikan abstraksi yang kuat untuk bekerja dengan data numerik dalam konteks machine learning dan deep learning, dan PyTorch memiliki fungsi-fungsi bawaan yang memungkinkan manipulasi tensor dengan cepat dan efisien.

Misalnya, Anda dapat mewakili gambar sebagai tensor dengan bentuk yang berarti , karena pada gambar memiliki saluran warna (merah, hijau, biru), tinggi piksel dan lebar piksel.`[3, 224, 224][colour_channels, height, width]` 3 224 224

![image.png](http://tinyurl.com/ten-sor)
Dalam Bahasa Tensor (the language used to describe tensors), tensor memiliki 3 dimensi, satu untuk `colour_channels`, `height` and `width`.




##Excerxise

###1. Import PyTorch

In [2]:
#Langkah 1: Import Pytorch
import torch
torch.__version__

'2.1.0+cu121'



```
import torch
torch.__version__
```
Prompt ini digunakan untuk import library pytorch dan cek versi dari pytorch yang akan digunakan.

Versi PyTorch "2.1.0+cu121" memiliki beberapa komponen informasi yang perlu diuraikan:



*   Versi PyTorch: "2.1.0" adalah nomor versi utama dari framework PyTorch. Versi utama biasanya menunjukkan rilis utama dengan fitur-fitur besar dan perubahan signifikan.
*   
"cu121": Ini merujuk pada versi CUDA yang kompatibel dengan PyTorch. CUDA adalah platform komputasi paralel NVIDIA yang memungkinkan pemrosesan pada unit pemrosesan grafis (GPU). Angka "cu121" menunjukkan versi spesifik dari CUDA yang digunakan oleh PyTorch. Dalam konteks ini, cu121 mungkin menunjukkan bahwa PyTorch ini dioptimalkan atau dikompilasi dengan CUDA versi 11.1.

Dengan kata lain, versi PyTorch "2.1.0+cu121" adalah versi 2.1.0 dari PyTorch yang dioptimalkan untuk bekerja dengan CUDA versi 11.1.

###2. Create a random tensor with shape (5, 5).

In [3]:
#Langkah 2: Membuat tensor acak dengan bentuk (5, 5)
tensor_random = torch.rand((5, 5))
print("Tensor Random:")
print(tensor_random)

Tensor Random:
tensor([[0.1181, 0.8425, 0.2857, 0.8821, 0.6899],
        [0.8326, 0.5486, 0.1789, 0.9693, 0.0614],
        [0.1282, 0.4121, 0.6586, 0.9687, 0.5189],
        [0.7525, 0.3302, 0.5909, 0.6254, 0.1549],
        [0.3638, 0.3933, 0.4496, 0.7604, 0.3068]])



Tensor yang diberikan adalah matriks 5x5 yang diisi dengan nilai acak antara 0 dan 1. Setiap elemen dalam matriks ini diperoleh secara acak dan independen.



```
tensor([[0.8310, 0.6656, 0.2738, 0.2169, 0.8778],
        [0.8703, 0.2049, 0.4429, 0.6630, 0.5918],
        [0.2628, 0.2938, 0.4055, 0.4889, 0.0480],
        [0.7309, 0.8305, 0.3950, 0.8399, 0.6490],
        [0.7485, 0.8342, 0.7028, 0.8583, 0.0659]])

```


*   Matriks ini memiliki 5 baris dan 5 kolom, sehingga ukurannya (shape) adalah (5, 5).
*   Setiap elemen matriks adalah nilai acak yang diambil dari distribusi uniform antara 0 dan 1. Nilai ini dapat digunakan untuk berbagai tujuan, seperti inisialisasi parameter dalam model machine learning atau percobaan acak.
*   Matriks ini dibuat menggunakan fungsi PyTorch torch.rand() yang menghasilkan tensor dengan elemen-elemen yang diambil dari distribusi acak seragam antara 0 dan 1.

###3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 5) (hint: you may have to transpose the second tensor)

In [4]:
#Langkah 3: Melakukan perkalian matriks pada tensor dari langkah 2 dengan tensor acak lain
tensor_2 = torch.rand((1, 5))
result = torch.matmul(tensor_random, tensor_2.t())  # Mengubah tensor kedua menjadi transpose
print("\nHasil Perkalian Matriks:")
print(result, tensor_2.shape)


Hasil Perkalian Matriks:
tensor([[1.0319],
        [0.9463],
        [1.0258],
        [1.0583],
        [0.8841]]) torch.Size([1, 5])


Hasil tersebut menunjukkan hasil perkalian matriks yang diberikan dalam bentuk tensor. Tensor ini memiliki dimensi atau ukuran torch.Size([1, 5]), yang berarti tensor tersebut merupakan matriks dengan 1 baris dan 5 kolom.

Setiap elemen di dalam matriks tersebut adalah hasil perkalian matriks sebelumnya. Jika Anda memiliki dua matriks, katakanlah A dengan dimensi m x n dan B dengan dimensi n x p, maka hasil perkalian matriks AB akan menghasilkan matriks dengan dimensi m x p. Dalam kasus ini, matriks inputnya mungkin memiliki dimensi 1 x n, dan hasil perkalian tersebut adalah matriks 1 x p.

Namun, tanpa informasi lebih lanjut tentang matriks input dan operasi perkalian matriks yang dilakukan, sulit untuk memberikan penjelasan lebih lanjut tentang makna sebenarnya dari hasil tersebut. Jika Anda memiliki matriks input dan operasi perkalian matriks yang digunakan, saya dapat memberikan penjelasan lebih rinci.

###4. Set the random seed to 0 and do 2 & 3 over again.

In [5]:
# Langkah 4: Mengatur benih acak menjadi 0 dan melakukan langkah 2 & 3 lagi
#Create Manual Seed
torch.manual_seed(0)

tensor_random = torch.rand((5, 5))
result = torch.matmul(tensor_random, tensor_2.t())
print("\nHasil Perkalian Matriks setelah Mengatur Benih Acak:")
print(result, result.shape)


Hasil Perkalian Matriks setelah Mengatur Benih Acak:
tensor([[0.7345],
        [1.5063],
        [0.5895],
        [0.9937],
        [1.2397]]) torch.Size([5, 1])


Pertama, perintah `torch.manual_seed(0)` mengatur benih acak PyTorch sehingga menghasilkan angka acak yang konsisten setiap kali kode dijalankan.

Selanjutnya, `tensor_random = torch.rand((5, 5))` membuat matriks acak berukuran 5x5 yang berisi nilai-nilai acak antara 0 dan 1.

Kemudian, `result = torch.matmul(tensor_random, tensor_2.t())` melakukan perkalian matriks antara tensor_random dengan transpos dari tensor_2. Hasil perkalian matriks ini disimpan dalam variabel result.

Akhirnya,`print(result, result.shape)` mencetak hasil perkalian matriks beserta bentuk `(shape)` dari tensor tersebut. Hasilnya adalah matriks kolom dengan 5 baris dan 1 kolom, yang sesuai dengan dimensi yang dicetak `(torch.Size([5, 1]))`.

Jadi, hasil perkalian matriks tersebut adalah matriks kolom dengan 5 baris dan 1 kolom yang diperoleh dari perkalian matriks tensor_random dengan transpos dari tensor_2.

###5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [6]:
# Langkah 5: Menyetel benih acak GPU ke 1234
torch.cuda.manual_seed(1234)


`torch.cuda.manual_seed(1234)` adalah perintah yang digunakan dalam lingkungan PyTorch untuk mengatur benih `(seed)` acak pada perangkat `CUDA (Compute Unified Device Architecture)`, yang digunakan untuk komputasi pada GPU. Dengan mengatur benih acak, Anda dapat mengontrol hasil angka acak yang dihasilkan oleh operasi-acak pada GPU, sehingga hasilnya dapat direproduksi secara konsisten.

Dalam konteks ini:


*   `torch.cuda.manual_seed()` digunakan untuk mengatur benih acak pada perangkat `CUDA (GPU)`.
*   `Angka 1234` adalah nilai benih yang ditetapkan. Mengatur benih dengan nilai tertentu memungkinkan Anda mendapatkan hasil acak yang sama setiap kali kode dijalankan, asalkan pengaturan benih yang sama juga digunakan pada operasi-acak lainnya.

###6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

In [10]:
# Langkah 6: Membuat dua tensor acak dengan bentuk (2, 3) dan mengirimkannya ke GPU
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_gpu_1 = torch.rand((2, 3), device='cuda')
tensor_gpu_2 = torch.rand((2, 3), device='cuda')
tensor_gpu_1,tensor_gpu_2

Device: cuda


(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.6208, 0.0276, 0.3255],
         [0.1114, 0.6812, 0.3608]], device='cuda:0'))

Output yang Anda berikan mencakup dua tensor, dan keduanya memiliki perangkat CUDA ('cuda:0') sebagai tempat penyimpanan. Hal ini menunjukkan bahwa operasi atau inisialisasi tensor tersebut terjadi pada perangkat GPU (CUDA).

Berikut adalah penjelasan rinci untuk setiap tensor:



1.   Tensor pertama:
```
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
```
Ini adalah tensor 2D dengan bentuk (shape) 2x3, yang berisi nilai-nilai acak. Tensor ini berada pada perangkat CUDA ('cuda:0'), yang berarti ia disimpan dan dioperasikan pada GPU.

2.   Tensor kedua:
```
# tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')
```
Ini juga adalah tensor 2D dengan bentuk 2x3 dan berisi nilai-nilai acak. Seperti tensor pertama, tensor kedua juga berada pada perangkat CUDA ('cuda:0').

Jadi, keseluruhan output menunjukkan dua tensor 2D dengan nilai-nilai acak yang diinisialisasi pada perangkat GPU. Kode atau operasi sebelum output ini dapat memberikan konteks lebih lanjut tentang bagaimana tensor-tensor ini dibuat atau dimanipulasi.




###7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [12]:
# Langkah 7: Melakukan perkalian matriks pada tensor yang dibuat dalam langkah 6
result_gpu = torch.matmul(tensor_gpu_1, tensor_gpu_2.t())  # Mengubah tensor kedua menjadi transpose
print("\nHasil Perkalian Matriks pada GPU:")
print(result_gpu, result_gpu.shape)


Hasil Perkalian Matriks pada GPU:
tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0') torch.Size([2, 2])



Hasil perkalian matriks `tensor_gpu_1 dan tensor_gpu_2.t` yang diberikan adalah tensor 2D dengan bentuk (shape) [2, 2]. Ini menunjukkan bahwa hasilnya adalah matriks berukuran 2x2. Tensor ini juga memiliki atribut device='cuda:0', yang berarti tensor tersebut disimpan dan dioperasikan pada perangkat GPU (CUDA) dengan ID 'cuda:0'.

###8. Find the maximum and minimum values of the output of 7.

In [13]:
# Langkah 8: Mencari nilai maksimum dan minimum dari output langkah 7
max_value = torch.max(result_gpu)
min_value = torch.min(result_gpu)
print("\nNilai Maksimum:", max_value.item())
print("Nilai Minimum:", min_value.item())


Nilai Maksimum: 0.7667766809463501
Nilai Minimum: 0.27863210439682007


*   torch.max(result_gpu): Ini menghitung nilai maksimum dari seluruh elemen dalam
tensor result_gpu. Hasilnya disimpan dalam variabel max_value.
*   torch.min(result_gpu): Ini menghitung nilai minimum dari seluruh elemen dalam tensor result_gpu. Hasilnya disimpan dalam variabel min_value.

Jadi, setelah menjalankan kode tersebut, max_value akan berisi nilai maksimum dari tensor result_gpu, dan min_value akan berisi nilai minimum dari tensor tersebut. Dalam konteks ini, result_gpu mungkin adalah tensor hasil perkalian matriks yang dioperasikan pada GPU, seperti yang telah Anda tunjukkan sebelumnya.

Informasi ini memberikan nilai maksimum dan minimum dari elemen-elemen dalam tensor. Dalam konteks ini, tensor yang dimaksud adalah hasil dari operasi perkalian matriks yang dilakukan pada GPU

###9. Find the maximum and minimum index values of the output of 7.

In [14]:
# Langkah 9: Mencari nilai indeks maksimum dan minimum dari output langkah 7
argmax_index = torch.argmax(result_gpu)
argmin_index = torch.argmin(result_gpu)
print("\nIndeks Maksimum:", argmax_index.item())
print("Indeks Minimum:", argmin_index.item())


Indeks Maksimum: 1
Indeks Minimum: 0


Kode tersebut menghitung indeks (posisi) dari nilai maksimum dan minimum dalam tensor result_gpu.

1.   torch.argmax(result_gpu): Ini mengembalikan indeks dari nilai maksimum dalam tensor result_gpu. Jadi, argmax_index akan berisi indeks dari nilai maksimum dalam tensor tersebut.
2.   torch.argmin(result_gpu): Ini mengembalikan indeks dari nilai minimum dalam tensor result_gpu. Jadi, argmin_index akan berisi indeks dari nilai minimum dalam tensor tersebut.


Kode tersebut menghitung indeks (posisi) dari nilai maksimum dan minimum dalam tensor result_gpu. Berikut adalah penjelasan singkat untuk setiap baris kode:

python
Copy code
argmax_index = torch.argmax(result_gpu)
argmin_index = torch.argmin(result_gpu)
torch.argmax(result_gpu): Ini mengembalikan indeks dari nilai maksimum dalam tensor result_gpu. Jadi, argmax_index akan berisi indeks dari nilai maksimum dalam tensor tersebut.

torch.argmin(result_gpu): Ini mengembalikan indeks dari nilai minimum dalam tensor result_gpu. Jadi, argmin_index akan berisi indeks dari nilai minimum dalam tensor tersebut.

Ketika kita memiliki tensor, argmax dan argmin berguna untuk mengetahui di mana posisi nilai maksimum dan minimum dalam tensor tersebut. Misalnya, jika argmax_index adalah (i, j), maka nilai maksimum terletak di baris ke-i dan kolom ke-j dalam tensor result_gpu. Begitu pula untuk argmin_index yang akan memberikan posisi nilai minimum dalam tensor tersebut.

Jadi, setelah menjalankan kode tersebut, argmax_index dan argmin_index akan berisi indeks dari nilai maksimum dan minimum dalam tensor result_gpu.



###10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [15]:
# Langkah 10: Membuat tensor acak dengan bentuk (1, 1, 1, 10) dan menghapus semua dimensi 1
torch.manual_seed(7)
tensor_random_4d = torch.rand((1, 1, 1, 10))
tensor_flat = tensor_random_4d.view(-1)
print("\nTensor Pertama dan Bentuknya:")
print(tensor_random_4d)
print(tensor_random_4d.shape)
print("\nTensor Kedua dan Bentuknya setelah Menghapus Dimensi 1:")
print(tensor_flat)
print(tensor_flat.shape)


Tensor Pertama dan Bentuknya:
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])

Tensor Kedua dan Bentuknya setelah Menghapus Dimensi 1:
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])


Penjelasan ini memberikan informasi tentang dua tensor dan perubahan bentuk (shape) yang terjadi. Mari kita jelaskan masing-masing bagian:


**Tensor Pertama dan Bentuknya:**
```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])

```



*   Tensor Pertama: Ini adalah tensor 4D. Nilai-nilai elemennya berada di dalam empat dimensi dengan panjang 1 pada setiap dimensi. Masing-masing dimensi adalah (1, 1, 1, 10).
*   Bentuk Tensor Pertama: [1, 1, 1, 10] menunjukkan bahwa tensor ini memiliki dimensi 1 pada dimensi pertama, 1 pada dimensi kedua, 1 pada dimensi ketiga, dan 10 pada dimensi keempat.


**Tensor Kedua dan Bentuknya setelah Menghapus Dimensi 1:**

```
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])

```

*   Tensor Kedua: Setelah menghapus dimensi yang memiliki panjang 1, tensor ini menjadi tensor 1D. Ini adalah daftar nilai tunggal tanpa dimensi tambahan.
*   Bentuk Tensor Kedua: [10] menunjukkan bahwa tensor ini sekarang hanya memiliki satu dimensi dengan panjang 10.

Jadi, perubahan dari tensor pertama ke tensor kedua melibatkan penghapusan dimensi yang memiliki panjang 1, menghasilkan tensor dengan dimensi yang lebih rendah.




